### ISSUE TITLE
A small alternative

### ISSUE THREAD

**Issue by leoguignard** [vallops99/Conda-autoactivate-env#1]
Hey,

Thanks for the piece of code, that's really helpful. A small suggestion that I am using on my side. I usually name my folders similarly to the conda env name. Therefore, this small modification could be helpful:
```shell
export CONDA_ENVS=`conda env list | tail +3 | cut -d' ' -f1`
export CONDACONFIGDIR=""
cd() { builtin cd "$@" &&
if [[ $CONDA_ENVS =~ (^|[[:space:]])${@##*/}($|[[:space:]]) ]]; then
    export CONDACONFIGDIR=$PWD
    conda activate ${@##*/}
elif [ -n $CONDACONFIGDIR ]; then
    if [[ $PWD != *"$CONDACONFIGDIR"* ]]; then
    export CONDACONFIGDIR=""
    conda deactivate
    fi
fi }
```
It checks whether the folder you are entering is the name of an environment if so, activates it.
There is one drawback: when starting the shell you need to store the list of environments, which is a tad slow, if you have any idea about how that could be done faster, I'd be glad to hear it!

Thanks again!

**Comment by vallops99** [comment]
Hey @leoguignard,

Thanks for your suggestion.

Speed execution aside, what I don't like about this edit is that, if you create a new env, you have to launch the shell's script again to let it work properly.
This happens because the list of environments is stored at shell startup.
So, in case you'd like this functionality a lot and you want to keep it, I propose the solution of launching `conda env list` inside the cd function to check wether an env with that name is present or not.
Obviously, this will slow down the cd function a lot.

```bash
export CURRENTENVDIR=""
cd() { builtin cd "$@" &&
if [[ ! -z `conda env list | cut -d' ' -f1 | grep -w ${@##*/}` ]]; then
    export CURRENTENVDIR=$PWD
    conda activate ${@##*/}
elif [ -n $CURRENTENVDIR ]; then
    if [[ $PWD != *"$CURRENTENVDIR"* ]]; then
    export CURRENTENVDIR=""
    conda deactivate
    fi
fi }
```
Furthermore, I don't like that the env could activate in another directory just because it has the same name.

The way of activating the env based on a config file came out from others environments managers (eg pyenv), that activate your environment automatically based on a .python-version file inside your folder.

Anyway, I'm still ok about digging on that for finding a better solution.

EDIT: I added the cut in the first IF of the code (it was bugging with home directory), by the way, that part could probably be made with awk command to speed up the process, but I don't think it will be so much quicker.

Cheers.
