### ISSUE TITLE
Deactivate logic is backwards?

### ISSUE THREAD

**Issue by sacsar** [vallops99/Conda-autoactivate-env#2]
Thank you for this, it's extremely useful.

I did find that the deactivation logic seems to be backwards and I had to get rid of the `-n`, giving:
```bash
  export CONDACONFIGDIR=""
  cd() { builtin cd "$@" &&
  if [ -f "$PWD"/.conda_config ]; then
      export CONDACONFIGDIR=$PWD
      conda activate "$(cat .conda_config)"
  elif [ "$CONDACONFIGDIR" ]; then
      if [[ $PWD != *"$CONDACONFIGDIR"* ]]; then
      export CONDACONFIGDIR=""
      conda deactivate
      fi
  fi }
```

**Comment by vallops99** [comment]
Hey @sacsar,

thanks for noticing this.
I did some tests and you're right, the logic is backwards.
The script works because the condition's result is an unexpected value, it always returns true (at least in my tests).

To clarify the unexpected value, I understood this:
`[ -n $CONDACONFIGDIR ]` --> TRUE in any case.
`[ -n "$CONDACONFIGDIR" ]` --> TRUE when string is zero length, false when string is non-zero length.

 OR

`[ -n $CONDACONFIGDIR ]` --> TRUE in any case.
`[[ -n $CONDACONFIGDIR ]]` --> TRUE when string is zero length, false when string is non-zero length.

Anyway, this is just the explanation of how the backwards logic is actually doing its work.
Your solution is the correct one for this script, I'll add it to the script.

By the way, I found this interesting thread on StackOverflow that talks about brackets and quoted variables inside condition:
[test-for-non-zero-length-string-in-bash-n-var-or-var](https://stackoverflow.com/questions/3869072/test-for-non-zero-length-string-in-bash-n-var-or-var)

Thanks a lot again!
